namespace: sorteos-live-dev
images:
  - name: harbor.coopetarrazu.com:8443/sorteos-live
    newName: harbor.coopetarrazu.com:8443/cluster/dev/sorteos-live/sorteos-live
    newTag: v1.0.0
resources:
  - ../../base
